# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import riva_nmt_pb2 as riva_dot_proto_dot_riva__nmt__pb2


class RivaTranslationStub(object):
    """
    RivaTranslation service provides rpcs to translate between languages.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranslateText = channel.unary_unary(
                '/nvidia.riva.nmt.RivaTranslation/TranslateText',
                request_serializer=riva_dot_proto_dot_riva__nmt__pb2.TranslateTextRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__nmt__pb2.TranslateTextResponse.FromString,
                )
        self.ListSupportedLanguagePairs = channel.unary_unary(
                '/nvidia.riva.nmt.RivaTranslation/ListSupportedLanguagePairs',
                request_serializer=riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageResponse.FromString,
                )
        self.StreamingTranslateSpeechToText = channel.stream_stream(
                '/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToText',
                request_serializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextResponse.FromString,
                )
        self.StreamingTranslateSpeechToSpeech = channel.stream_stream(
                '/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToSpeech',
                request_serializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechResponse.FromString,
                )


class RivaTranslationServicer(object):
    """
    RivaTranslation service provides rpcs to translate between languages.

    """

    def TranslateText(self, request, context):
        """Translate text to text, from a source to a target language.  Currently
        source and target language fields is required, along with the model name.
        Multiple texts may be passed per request up to the given batch size for the
        model, which is set at translation pipeline creation time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSupportedLanguagePairs(self, request, context):
        """Lists the available language pairs and models names to be used for
        TranslateText
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingTranslateSpeechToText(self, request_iterator, context):
        """streaming speech to text translation api.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingTranslateSpeechToSpeech(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RivaTranslationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=riva_dot_proto_dot_riva__nmt__pb2.TranslateTextRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__nmt__pb2.TranslateTextResponse.SerializeToString,
            ),
            'ListSupportedLanguagePairs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedLanguagePairs,
                    request_deserializer=riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageResponse.SerializeToString,
            ),
            'StreamingTranslateSpeechToText': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingTranslateSpeechToText,
                    request_deserializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextResponse.SerializeToString,
            ),
            'StreamingTranslateSpeechToSpeech': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingTranslateSpeechToSpeech,
                    request_deserializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.riva.nmt.RivaTranslation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RivaTranslation(object):
    """
    RivaTranslation service provides rpcs to translate between languages.

    """

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nvidia.riva.nmt.RivaTranslation/TranslateText',
            riva_dot_proto_dot_riva__nmt__pb2.TranslateTextRequest.SerializeToString,
            riva_dot_proto_dot_riva__nmt__pb2.TranslateTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSupportedLanguagePairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nvidia.riva.nmt.RivaTranslation/ListSupportedLanguagePairs',
            riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageRequest.SerializeToString,
            riva_dot_proto_dot_riva__nmt__pb2.AvailableLanguageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingTranslateSpeechToText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToText',
            riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextRequest.SerializeToString,
            riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingTranslateSpeechToSpeech(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToSpeech',
            riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechRequest.SerializeToString,
            riva_dot_proto_dot_riva__nmt__pb2.StreamingTranslateSpeechToSpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
