# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import riva_tts_pb2 as riva_dot_proto_dot_riva__tts__pb2


class RivaSpeechSynthesisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/nvidia.riva.tts.RivaSpeechSynthesis/Synthesize',
                request_serializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.FromString,
                )
        self.SynthesizeOnline = channel.unary_stream(
                '/nvidia.riva.tts.RivaSpeechSynthesis/SynthesizeOnline',
                request_serializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.FromString,
                )
        self.GetRivaSynthesisConfig = channel.unary_unary(
                '/nvidia.riva.tts.RivaSpeechSynthesis/GetRivaSynthesisConfig',
                request_serializer=riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigRequest.SerializeToString,
                response_deserializer=riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigResponse.FromString,
                )


class RivaSpeechSynthesisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Used to request text-to-speech from the service. Submit a request
        containing the desired text and configuration, and receive audio bytes in
        the requested format.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeOnline(self, request, context):
        """Used to request text-to-speech returned via stream as it becomes available.
        Submit a SynthesizeSpeechRequest with desired text and configuration,
        and receive stream of bytes in the requested format.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRivaSynthesisConfig(self, request, context):
        """Enables clients to request the configuration of the current Synthesize
        service, or a specific model within the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RivaSpeechSynthesisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.SerializeToString,
            ),
            'SynthesizeOnline': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeOnline,
                    request_deserializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.SerializeToString,
            ),
            'GetRivaSynthesisConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRivaSynthesisConfig,
                    request_deserializer=riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigRequest.FromString,
                    response_serializer=riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.riva.tts.RivaSpeechSynthesis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RivaSpeechSynthesis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nvidia.riva.tts.RivaSpeechSynthesis/Synthesize',
            riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
            riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SynthesizeOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nvidia.riva.tts.RivaSpeechSynthesis/SynthesizeOnline',
            riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
            riva_dot_proto_dot_riva__tts__pb2.SynthesizeSpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRivaSynthesisConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nvidia.riva.tts.RivaSpeechSynthesis/GetRivaSynthesisConfig',
            riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigRequest.SerializeToString,
            riva_dot_proto_dot_riva__tts__pb2.RivaSynthesisConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
