#!/usr/bin/expect -f

# Set script to use utf-8 encoding
fconfigure stdout -encoding utf-8

# Assign arguments to variables
set api_key [lindex $argv 0]
set org [lindex $argv 1]

set username "\$oauthtoken"

# Start the docker login command
spawn docker login nvcr.io

# Expect "Username" prompt
expect "Username:"
send "$username\r"

# Expect "Password" prompt
expect "Password:"
send "$api_key\r"

# Wait for the command to complete
expect eof

# Run set command
spawn /opt/ngc-cli/ngc config set

# Run the configuration command
spawn /opt/ngc-cli/ngc config set
expect "Enter API key:"
send -- "$api_key\r"
expect "Enter CLI output format type \\\[json\\\]. Choices: \\\['ascii', 'csv', 'json'\\\]"
send -- "json\r"
send -- "$org\r"
expect "Enter team \\\[no-team\\\]. Choices: \\\['no-team'\\\]"
send -- "no-team\r"
expect "Enter ace \\\[no-ace\\\]. Choices: \\\['no-ace'\\\]"
send -- "no-ace\r"
expect eof

puts "Configuration updated successfully with org set to $org"
